// Permission types
export type Permission = 'CREATE' | 'READ' | 'UPDATE' | 'DELETE';

// Role types based on PRD
export type Role = 
  | 'FOUNDER'
  | 'SUPER_ADMIN'
  | 'FINANCE_CONTROLLER'
  | 'PRODUCT_OWNER'
  | 'OPS_MANAGER'
  | 'TECH_LEAD'
  | 'STRATEGY_LEAD'
  | 'SALES_LEAD'
  | 'INVESTOR'
  | 'PILOT_CLIENT'
  | 'ADVISOR'
  | 'TEAM';

// Module types based on PRD
export type Module = 
  | 'USER_MANAGEMENT'
  | 'CAPITAL_USAGE_BUDGET'
  | 'MVP_MILESTONE_PROGRESS'
  | 'BURN_RATE_RUNWAY'
  | 'FINANCIAL_PROJECTIONS'
  | 'HIRING_HEADCOUNT_PLAN'
  | 'INVESTOR_REPORT_GENERATOR'
  | 'KPI_DASHBOARD'
  | 'ROADMAP_TIMELINE_VIEW'
  | 'DEV_PROGRESS_INFRA_STATUS'
  | 'DELIVERY_NETWORK_METRICS'
  | 'PILOT_CLIENT_PERFORMANCE_VIEW'
  | 'COMPLIANCE_RISK_LOGS';

// Permission matrix based on PRD
const PERMISSION_MATRIX: Record<Role, Record<Module, Permission[]>> = {
  FOUNDER: {
    USER_MANAGEMENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
    CAPITAL_USAGE_BUDGET: ['READ', 'UPDATE'],
    MVP_MILESTONE_PROGRESS: ['READ', 'UPDATE'],
    BURN_RATE_RUNWAY: ['READ', 'UPDATE'],
    FINANCIAL_PROJECTIONS: ['READ', 'UPDATE'],
    HIRING_HEADCOUNT_PLAN: ['READ', 'UPDATE'],
    INVESTOR_REPORT_GENERATOR: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
    KPI_DASHBOARD: ['READ', 'UPDATE'],
    ROADMAP_TIMELINE_VIEW: ['READ', 'UPDATE'],
    DEV_PROGRESS_INFRA_STATUS: ['READ'],
    DELIVERY_NETWORK_METRICS: ['READ'],
    PILOT_CLIENT_PERFORMANCE_VIEW: ['READ'],
    COMPLIANCE_RISK_LOGS: ['READ', 'UPDATE'],
  },
  SUPER_ADMIN: {
    USER_MANAGEMENT: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
    CAPITAL_USAGE_BUDGET: ['READ', 'UPDATE'],
    MVP_MILESTONE_PROGRESS: ['READ', 'UPDATE'],
    BURN_RATE_RUNWAY: ['READ', 'UPDATE'],
    FINANCIAL_PROJECTIONS: ['READ', 'UPDATE'],
    HIRING_HEADCOUNT_PLAN: ['READ', 'UPDATE'],
    INVESTOR_REPORT_GENERATOR: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
    KPI_DASHBOARD: ['READ', 'UPDATE'],
    ROADMAP_TIMELINE_VIEW: ['READ', 'UPDATE'],
    DEV_PROGRESS_INFRA_STATUS: ['READ'],
    DELIVERY_NETWORK_METRICS: ['READ'],
    PILOT_CLIENT_PERFORMANCE_VIEW: ['READ'],
    COMPLIANCE_RISK_LOGS: ['READ', 'UPDATE'],
  },
  FINANCE_CONTROLLER: {
    USER_MANAGEMENT: [],
    CAPITAL_USAGE_BUDGET: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
    MVP_MILESTONE_PROGRESS: ['READ'],
    BURN_RATE_RUNWAY: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
    FINANCIAL_PROJECTIONS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
    HIRING_HEADCOUNT_PLAN: ['READ', 'UPDATE'],
    INVESTOR_REPORT_GENERATOR: ['CREATE', 'READ', 'UPDATE'],
    KPI_DASHBOARD: ['READ', 'UPDATE'],
    ROADMAP_TIMELINE_VIEW: ['READ'],
    DEV_PROGRESS_INFRA_STATUS: [],
    DELIVERY_NETWORK_METRICS: ['READ'],
    PILOT_CLIENT_PERFORMANCE_VIEW: [],
    COMPLIANCE_RISK_LOGS: ['READ', 'UPDATE'],
  },
  PRODUCT_OWNER: {
    USER_MANAGEMENT: [],
    CAPITAL_USAGE_BUDGET: ['READ'],
    MVP_MILESTONE_PROGRESS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
    BURN_RATE_RUNWAY: ['READ'],
    FINANCIAL_PROJECTIONS: ['READ'],
    HIRING_HEADCOUNT_PLAN: ['READ'],
    INVESTOR_REPORT_GENERATOR: ['READ', 'UPDATE'],
    KPI_DASHBOARD: ['READ', 'UPDATE'],
    ROADMAP_TIMELINE_VIEW: ['CREATE', 'READ', 'UPDATE'],
    DEV_PROGRESS_INFRA_STATUS: ['READ'],
    DELIVERY_NETWORK_METRICS: ['READ'],
    PILOT_CLIENT_PERFORMANCE_VIEW: ['READ'],
    COMPLIANCE_RISK_LOGS: ['READ'],
  },
  OPS_MANAGER: {
    USER_MANAGEMENT: [],
    CAPITAL_USAGE_BUDGET: [],
    MVP_MILESTONE_PROGRESS: ['READ'],
    BURN_RATE_RUNWAY: [],
    FINANCIAL_PROJECTIONS: [],
    HIRING_HEADCOUNT_PLAN: ['READ', 'UPDATE'],
    INVESTOR_REPORT_GENERATOR: [],
    KPI_DASHBOARD: ['READ', 'UPDATE'],
    ROADMAP_TIMELINE_VIEW: ['READ'],
    DEV_PROGRESS_INFRA_STATUS: [],
    DELIVERY_NETWORK_METRICS: ['CREATE', 'READ', 'UPDATE'],
    PILOT_CLIENT_PERFORMANCE_VIEW: ['READ'],
    COMPLIANCE_RISK_LOGS: [],
  },
  TECH_LEAD: {
    USER_MANAGEMENT: [],
    CAPITAL_USAGE_BUDGET: [],
    MVP_MILESTONE_PROGRESS: ['READ', 'UPDATE'],
    BURN_RATE_RUNWAY: [],
    FINANCIAL_PROJECTIONS: [],
    HIRING_HEADCOUNT_PLAN: ['READ'],
    INVESTOR_REPORT_GENERATOR: [],
    KPI_DASHBOARD: ['READ', 'UPDATE'],
    ROADMAP_TIMELINE_VIEW: ['READ'],
    DEV_PROGRESS_INFRA_STATUS: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
    DELIVERY_NETWORK_METRICS: [],
    PILOT_CLIENT_PERFORMANCE_VIEW: [],
    COMPLIANCE_RISK_LOGS: [],
  },
  STRATEGY_LEAD: {
    USER_MANAGEMENT: [],
    CAPITAL_USAGE_BUDGET: ['READ'],
    MVP_MILESTONE_PROGRESS: ['READ', 'UPDATE'],
    BURN_RATE_RUNWAY: ['READ'],
    FINANCIAL_PROJECTIONS: ['READ'],
    HIRING_HEADCOUNT_PLAN: ['READ'],
    INVESTOR_REPORT_GENERATOR: ['CREATE', 'READ'],
    KPI_DASHBOARD: ['READ', 'UPDATE'],
    ROADMAP_TIMELINE_VIEW: ['CREATE', 'READ', 'UPDATE'],
    DEV_PROGRESS_INFRA_STATUS: ['READ'],
    DELIVERY_NETWORK_METRICS: ['READ'],
    PILOT_CLIENT_PERFORMANCE_VIEW: ['READ'],
    COMPLIANCE_RISK_LOGS: ['READ', 'UPDATE'],
  },
  SALES_LEAD: {
    USER_MANAGEMENT: [],
    CAPITAL_USAGE_BUDGET: ['READ'],
    MVP_MILESTONE_PROGRESS: ['READ'],
    BURN_RATE_RUNWAY: ['READ'],
    FINANCIAL_PROJECTIONS: ['READ'],
    HIRING_HEADCOUNT_PLAN: ['READ', 'UPDATE'],
    INVESTOR_REPORT_GENERATOR: ['READ'],
    KPI_DASHBOARD: ['READ', 'UPDATE'],
    ROADMAP_TIMELINE_VIEW: ['READ'],
    DEV_PROGRESS_INFRA_STATUS: [],
    DELIVERY_NETWORK_METRICS: ['READ'],
    PILOT_CLIENT_PERFORMANCE_VIEW: ['READ'],
    COMPLIANCE_RISK_LOGS: [],
  },
  INVESTOR: {
    USER_MANAGEMENT: [],
    CAPITAL_USAGE_BUDGET: ['READ'],
    MVP_MILESTONE_PROGRESS: ['READ'],
    BURN_RATE_RUNWAY: ['READ'],
    FINANCIAL_PROJECTIONS: ['READ'],
    HIRING_HEADCOUNT_PLAN: ['READ'],
    INVESTOR_REPORT_GENERATOR: ['READ'],
    KPI_DASHBOARD: ['READ'],
    ROADMAP_TIMELINE_VIEW: ['READ'],
    DEV_PROGRESS_INFRA_STATUS: ['READ'],
    DELIVERY_NETWORK_METRICS: ['READ'],
    PILOT_CLIENT_PERFORMANCE_VIEW: [],
    COMPLIANCE_RISK_LOGS: [],
  },
  PILOT_CLIENT: {
    USER_MANAGEMENT: [],
    CAPITAL_USAGE_BUDGET: [],
    MVP_MILESTONE_PROGRESS: [],
    BURN_RATE_RUNWAY: [],
    FINANCIAL_PROJECTIONS: [],
    HIRING_HEADCOUNT_PLAN: [],
    INVESTOR_REPORT_GENERATOR: [],
    KPI_DASHBOARD: ['READ'],
    ROADMAP_TIMELINE_VIEW: [],
    DEV_PROGRESS_INFRA_STATUS: [],
    DELIVERY_NETWORK_METRICS: [],
    PILOT_CLIENT_PERFORMANCE_VIEW: ['READ'],
    COMPLIANCE_RISK_LOGS: [],
  },
  ADVISOR: {
    USER_MANAGEMENT: [],
    CAPITAL_USAGE_BUDGET: ['READ'],
    MVP_MILESTONE_PROGRESS: ['READ'],
    BURN_RATE_RUNWAY: ['READ'],
    FINANCIAL_PROJECTIONS: ['READ'],
    HIRING_HEADCOUNT_PLAN: ['READ'],
    INVESTOR_REPORT_GENERATOR: ['READ'],
    KPI_DASHBOARD: ['READ'],
    ROADMAP_TIMELINE_VIEW: ['READ'],
    DEV_PROGRESS_INFRA_STATUS: ['READ'],
    DELIVERY_NETWORK_METRICS: ['READ'],
    PILOT_CLIENT_PERFORMANCE_VIEW: ['READ'],
    COMPLIANCE_RISK_LOGS: ['READ'],
  },
  TEAM: {
    USER_MANAGEMENT: [],
    CAPITAL_USAGE_BUDGET: ['READ'],
    MVP_MILESTONE_PROGRESS: ['READ'],
    BURN_RATE_RUNWAY: ['READ'],
    FINANCIAL_PROJECTIONS: ['READ'],
    HIRING_HEADCOUNT_PLAN: ['READ'],
    INVESTOR_REPORT_GENERATOR: ['READ'],
    KPI_DASHBOARD: ['READ'],
    ROADMAP_TIMELINE_VIEW: ['READ'],
    DEV_PROGRESS_INFRA_STATUS: ['READ'],
    DELIVERY_NETWORK_METRICS: ['READ'],
    PILOT_CLIENT_PERFORMANCE_VIEW: ['READ'],
    COMPLIANCE_RISK_LOGS: ['READ'],
  },
};

// Check if user has permission for a specific module and action
export function hasPermission(
  userRole: Role,
  module: Module,
  permission: Permission
): boolean {
  const modulePermissions = PERMISSION_MATRIX[userRole]?.[module] || [];
  return modulePermissions.includes(permission);
}

// Check if user has any permission for a module
export function hasAnyPermission(userRole: Role, module: Module): boolean {
  const modulePermissions = PERMISSION_MATRIX[userRole]?.[module] || [];
  return modulePermissions.length > 0;
}

// Get all permissions for a user role and module
export function getPermissions(userRole: Role, module: Module): Permission[] {
  return PERMISSION_MATRIX[userRole]?.[module] || [];
}

// Check if user can access a specific route/page
export function canAccessRoute(userRole: Role, route: string): boolean {
  const routeModuleMap: Record<string, Module> = {
    '/': 'KPI_DASHBOARD',
    '/dashboard': 'KPI_DASHBOARD',
    '/team': 'HIRING_HEADCOUNT_PLAN',
    '/milestones': 'MVP_MILESTONE_PROGRESS',
    '/budget': 'CAPITAL_USAGE_BUDGET',
    '/analytics': 'KPI_DASHBOARD',
    '/reports': 'INVESTOR_REPORT_GENERATOR',
    '/roadmap': 'ROADMAP_TIMELINE_VIEW',
    '/settings': 'USER_MANAGEMENT',
  };

  const targetModule = routeModuleMap[route];
  if (!targetModule) return true; // Allow access to unknown routes for now

  return hasAnyPermission(userRole, targetModule);
}

// Role hierarchy for admin functions
export const ADMIN_ROLES: Role[] = ['FOUNDER', 'SUPER_ADMIN'];
export const MANAGER_ROLES: Role[] = ['FOUNDER', 'SUPER_ADMIN', 'FINANCE_CONTROLLER', 'PRODUCT_OWNER', 'OPS_MANAGER'];

export function isAdmin(role: Role): boolean {
  return ADMIN_ROLES.includes(role);
}

export function isManager(role: Role): boolean {
  return MANAGER_ROLES.includes(role);
} 